@api = http://localhost:3000/prestamos

GET {{api}}
###
POST {{api}}
Content-Type: application/json

{
    "FCHA_EMISION": "2023-09-17",
    "VENCE": "2023-10-17",
    "ID_LIBRO": "0075",
    "ID_LECTOR": "4",
    "DEVOLUCION": true
}

###
GET {{api}}/24

###
DELETE {{api}}/29

###
PUT {{api}}/24
Content-Type: application/json

{
  "id": 24,
  "FCHA_EMISION": "2023-07-07",
  "VENCE": "2023-08-06",
  "ID_LIBRO": "0074",
  "ID_LECTOR": "3",
  "DEVOLUCION": true
}