/****** Object:  Table [dbo].[AUTOR]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[AUTOR](
	[ID_AUTOR] [nvarchar](30) NOT NULL,
	[NOMBRE] [nvarchar](30) NULL,
	[NACIONALIDAD] [nvarchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_AUTOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
