/****** Object:  Table [dbo].[CENTRO_ESTUDIO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[CENTRO_ESTUDIO](
	[ID_cESTUDIO] [nvarchar](15) NOT NULL,
	[NOMBRE] [nvarchar](30) NULL,
	[TELEFONO] [nvarchar](8) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[ID_COMUNIDAD] [nvarchar](20) NULL,
 CONSTRAINT [PK__CENTRO_E__0FA47F46943D227E] PRIMARY KEY CLUSTERED 
(
	[ID_cESTUDIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[CENTRO_ESTUDIO]  WITH CHECK ADD  CONSTRAINT [FK__CENTRO_ES__ID_CO__3B75D760] FOREIGN KEY([ID_COMUNIDAD])
REFERENCES [dbo].[COMUNIDAD] ([ID_COMUNIDAD])
ALTER TABLE [dbo].[CENTRO_ESTUDIO] CHECK CONSTRAINT [FK__CENTRO_ES__ID_CO__3B75D760]
