/****** Object:  Table [dbo].[DESIDERATA]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[DESIDERATA](
	[ID_DSDT] [nvarchar](30) NOT NULL,
	[FCHA_EMISION] [date] NULL,
	[ID_LIBRO] [nvarchar](30) NULL,
	[AUTOR] [nvarchar](30) NULL,
	[EDITORIAL] [nvarchar](30) NULL,
	[ID_LECTOR] [nvarchar](30) NOT NULL,
	[ID_CENTRO] [nvarchar](20) NULL,
 CONSTRAINT [PK__DESIDERA__56D5DCB971750100] PRIMARY KEY CLUSTERED 
(
	[ID_DSDT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_DESIDERATA] UNIQUE NONCLUSTERED 
(
	[ID_LIBRO] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[DESIDERATA]  WITH CHECK ADD  CONSTRAINT [FK_DESIDERATA_LECTORES] FOREIGN KEY([ID_LECTOR])
REFERENCES [dbo].[LECTORES] ([ID_LECTOR])
ALTER TABLE [dbo].[DESIDERATA] CHECK CONSTRAINT [FK_DESIDERATA_LECTORES]
