/****** Object:  Table [dbo].[EDITORIAL]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EDITORIAL](
	[ID_EDITORIAL] [nvarchar](30) NOT NULL,
	[NOMBRE] [nvarchar](20) NULL,
	[TELEFONO] [nvarchar](8) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[DIRECCION] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_EDITORIAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
