/****** Object:  Table [dbo].[LECTORES]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LECTORES](
	[ID_LECTOR] [nvarchar](30) NOT NULL,
	[NOMBRE] [nvarchar](50) NULL,
	[APELLIDO] [nvarchar](50) NULL,
	[EDAD] [int] NULL,
	[TELEFONO] [nvarchar](15) NULL,
	[SEXO] [nvarchar](10) NULL,
	[ESTADO] [nvarchar](15) NULL,
	[OCUPACION] [nvarchar](50) NULL,
	[DIRECCION] [nvarchar](60) NULL,
	[OBSERVACION] [nvarchar](60) NULL,
	[ID_cESTUDIO] [nvarchar](15) NULL,
	[ID_cTRABAJO] [nvarchar](10) NULL,
	[NIVEL_ESCOLARIDAD] [nvarchar](20) NULL,
 CONSTRAINT [PK__LECTORES__147501AE8772F656] PRIMARY KEY CLUSTERED 
(
	[ID_LECTOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[LECTORES] SET (LOCK_ESCALATION = DISABLE)
ALTER TABLE [dbo].[LECTORES]  WITH CHECK ADD  CONSTRAINT [FK__LECTORES__ID_cES__3E52440B] FOREIGN KEY([ID_cESTUDIO])
REFERENCES [dbo].[CENTRO_ESTUDIO] ([ID_cESTUDIO])
ALTER TABLE [dbo].[LECTORES] CHECK CONSTRAINT [FK__LECTORES__ID_cES__3E52440B]
ALTER TABLE [dbo].[LECTORES]  WITH CHECK ADD  CONSTRAINT [FK__LECTORES__ID_cTR__3F466844] FOREIGN KEY([ID_cTRABAJO])
REFERENCES [dbo].[CENTRO_TRABAJO] ([ID_cTRABAJO])
ALTER TABLE [dbo].[LECTORES] CHECK CONSTRAINT [FK__LECTORES__ID_cTR__3F466844]
