/****** Object:  Table [dbo].[LIBROS]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[LIBROS](
	[ID_LIBRO] [nvarchar](30) NOT NULL,
	[ID_AUTOR] [nvarchar](30) NULL,
	[TITULO] [nvarchar](100) NULL,
	[EDICION] [nvarchar](30) NULL,
	[GENERO] [nvarchar](30) NULL,
	[ESTADO] [nvarchar](20) NULL,
	[ID_EDITORIAL] [nvarchar](30) NULL,
 CONSTRAINT [PK__LIBROS__93FF0A069F235E46] PRIMARY KEY CLUSTERED 
(
	[ID_LIBRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[LIBROS]  WITH CHECK ADD  CONSTRAINT [FK__LIBROS__ID_AUTOR__44FF419A] FOREIGN KEY([ID_AUTOR])
REFERENCES [dbo].[AUTOR] ([ID_AUTOR])
ALTER TABLE [dbo].[LIBROS] CHECK CONSTRAINT [FK__LIBROS__ID_AUTOR__44FF419A]
ALTER TABLE [dbo].[LIBROS]  WITH CHECK ADD  CONSTRAINT [FK__LIBROS__ID_EDITO__45F365D3] FOREIGN KEY([ID_EDITORIAL])
REFERENCES [dbo].[EDITORIAL] ([ID_EDITORIAL])
ALTER TABLE [dbo].[LIBROS] CHECK CONSTRAINT [FK__LIBROS__ID_EDITO__45F365D3]
