/****** Object:  Table [dbo].[MUNICIPIO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[MUNICIPIO](
	[ID_MUNICIPIO] [nvarchar](30) NOT NULL,
	[NOMBRE] [nvarchar](50) NULL,
	[ID_DEPARTAMENTO] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_MUNICIPIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[MUNICIPIO]  WITH CHECK ADD  CONSTRAINT [FK__MUNICIPIO__ID_DE__300424B4] FOREIGN KEY([ID_DEPARTAMENTO])
REFERENCES [dbo].[DEPARTAMENTO] ([ID_DEPARTAMENTO])
ON UPDATE CASCADE
ON DELETE CASCADE
ALTER TABLE [dbo].[MUNICIPIO] CHECK CONSTRAINT [FK__MUNICIPIO__ID_DE__300424B4]
