/****** Object:  Table [dbo].[PRESTAMO]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[PRESTAMO](
	[ID_PRESTAMO] [int] IDENTITY(1,1) NOT NULL,
	[FCHA_EMISION] [date] NULL,
	[VENCE] [date] NULL,
	[ID_LIBRO] [nvarchar](30) NOT NULL,
	[ID_LECTOR] [nvarchar](30) NOT NULL,
	[DEVOLUCION] [bit] NOT NULL,
 CONSTRAINT [PK__PRESTAMO__3D5A1E6C492FEF46] PRIMARY KEY CLUSTERED 
(
	[ID_PRESTAMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[PRESTAMO] ADD  CONSTRAINT [DF_PRESTAMO_DEVOLUCION]  DEFAULT ((0)) FOR [DEVOLUCION]
ALTER TABLE [dbo].[PRESTAMO]  WITH CHECK ADD  CONSTRAINT [FK__PRESTAMO__ID_LEC__49C3F6B7] FOREIGN KEY([ID_LECTOR])
REFERENCES [dbo].[LECTORES] ([ID_LECTOR])
ALTER TABLE [dbo].[PRESTAMO] CHECK CONSTRAINT [FK__PRESTAMO__ID_LEC__49C3F6B7]
ALTER TABLE [dbo].[PRESTAMO]  WITH CHECK ADD  CONSTRAINT [FK__PRESTAMO__ID_LIB__48CFD27E] FOREIGN KEY([ID_LIBRO])
REFERENCES [dbo].[LIBROS] ([ID_LIBRO])
ON UPDATE CASCADE
ALTER TABLE [dbo].[PRESTAMO] CHECK CONSTRAINT [FK__PRESTAMO__ID_LIB__48CFD27E]
